# Generated by Django 4.1.3 on 2023-05-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
