# Generated by Django 4.1.3 on 2023-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHR', '0003_patient_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.ImageField(blank=True, upload_to='prescription/')),
            ],
        ),
    ]
