# Generated by Django 4.1.3 on 2023-06-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHR', '0005_alter_history_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='prescription',
            field=models.FileField(blank=True, upload_to='prescrip/'),
        ),
    ]
