# Generated by Django 4.2.4 on 2023-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHR', '0008_hospitalmaster_alter_prescription_detail_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_detail',
            name='document',
            field=models.FileField(blank=True, upload_to='prescription/'),
        ),
    ]
